name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Android64
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64
          sdk: latest
          cli: latest

      - name: Upload Geode
        uses: actions/upload-artifact@v4
        with:
          name: StereoMadnessAutoPlay-Android64
          path: ${{ steps.build.outputs.build-output }}
